export default [
  {
    id: '0',
    title: 'Table Mountain Cableway, CapeTown ',
    image: '/img/cape-town-cable.jpg',
    blur: '/img/cape-town-cable-blur.jpg',
    description: "An image of the world famous cableway that travels between Table Mountain and Lion's Head in Cape Town.",
    tags: ['table-mountain', 'cape-town', 'cable-cart', 'lions-head'],
  },
  {
    id: '1',
    title: 'Table Mountain with Airplane and Sky Banner',
    image: '/img/airplane.jpg',
    blur: '/img/airplane-blur.jpg',
    description: 'Banner Ad Plane is often seen of the Cape Town airspace. So we will ask the people in Cape Town Howzit!',
    tags: ['cape-town', 'table-mountain', 'plane', 'red', 'sky-banner'],
  },
  {
    id: '2',
    title: 'Muizenberg Colored Beach Huts,  Cape Town',
    image: '/img/muizenberg-beach.jpg',
    blur: '/img/muizenberg-beach-blur.jpg',
    description: 'These colourful beach huts are a sight to be seen on the beach of Muizenberg in Cape Town, South Africa.',
    tags: ['cape-town', 'south-africa', 'muizenberg', 'huts', 'beach'],
  },
  {
    id: '3',
    title: 'Green Point Lighthouse, Cape Town',
    image: '/img/lighthouse.jpg',
    blur: '/img/lighthouse-blur.jpg',
    description:
      'First lit on 12 April 1824, it is located on Mouille Point, This lighthouse is still operational to this day and is one of the most famous landmarks in Green Point',
    tags: ['cape-town', 'south-africa', 'green-point', 'lighthouse', 'red', 'white'],
  },
  {
    id: '4',
    title: 'We have nothing to fever but running out of beer',
    image: '/img/beer.jpg',
    blur: '/img/beer-blur.jpg',
    description: 'A joke out of the hit animated tv series <strong>Futurama</strong>. ',
    tags: ['flag', 'america', 'strips', 'stars'],
  },
  {
    id: '5',
    title: 'Cute Black and White Skull Pattern',
    image: '/img/skulls.jpg',
    blur: '/img/skulls-blur.jpg',
    description:
      'A stack of black and white skulls piled over each other. This design is ideal for the Halloween season and not too scary for the little ones.',
    tags: ['skulls', 'cute', 'black', 'white'],
  },
  {
    id: '6',
    title: 'Just Be Your #Selfie',
    image: '/img/selfie.jpg',
    blur: '/img/selfie-blur.jpg',
    description:
      'Just a funny saying to let people know to just be themself when taking a selfie. With image of' + ' camara and some hearts',
    tags: ['selfie', 'fun', 'camara', 'hearts'],
  },
  {
    id: '7',
    title: "Happy St. Patrick's day",
    image: '/img/happy-st.jpg',
    blur: '/img/happy-st-blur.jpg',
    description: "Celebrate St. Patrick's day with this green t-shirt with some beer, shamrocks, and a fun green rainbow pattern.",
    tags: ['flag', 'america', 'strips', 'stars'],
  },
  {
    id: '8',
    title: 'One in a Melon, Watermelon',
    image: '/img/melon.jpg',
    blur: '/img/melon-blur.jpg',
    description: 'Tell people that you know that you are one in a million in a funny way by saying melon instead of million.',
    tags: ['melon', 'watermelon', 'funny', 'million', 'green', 'red'],
  },
  {
    id: '9',
    title: 'Cute Girl Skull With Pink Bow On Head',
    image: '/img/skully-girl.jpg',
    blur: '/img/skully-girl-blur.jpg',
    description: 'Just a cute little skull girl call skully with a cute pink little bow with a yellow flower on it.',
    tags: ['skull', 'cute', 'bow', 'pink', 'girl', 'skully'],
  },
  {
    id: '10',
    title: 'I Just Donut Care!',
    image: '/img/donut.jpg',
    blur: '/img/donut-blur.jpg',
    description: 'Let the masses know in a funny way that you just don’t care by using a donut.',
    tags: ['care', 'food', 'donut', 'pink', 'yellow'],
  },
]
